#!/usr/bin/env python3
# Generated by AI - Please review for correctness before using

import matplotlib.pyplot as plt


def add_data(euler1, euler2, euler3):
    """
    Add new Euler angle data to the storage lists.

    Args:
        euler1: Tuple/list of 3 values representing [axis_angle_1, axis_angle_2, axis_angle_3]
        euler2: Tuple/list of 3 values for second angle set
        euler3: Tuple/list of 3 values for third angle set

    The function will append each value to its respective storage list
    and update the time counter.
    """
    global t, data1_x, data1_y, data1_z, data2_x, data2_y, data2_z, data3_x, data3_y, data3_z

    t.append(t[-1] + TIME_INTERVAL)
    data1_x.append(euler1[0])
    data1_y.append(euler1[1])
    data1_z.append(euler1[2])
    data2_x.append(euler2[0])
    data2_y.append(euler2[1])
    data2_z.append(euler2[2])
    data3_x.append(euler3[0])
    data3_y.append(euler3[1])
    data3_z.append(euler3[2])


def plot_data():
    """
    Plot the Euler angle data with three subplots (one per axis).
    Clears previous plots and draws all stored data.

    Returns:
        Figure object for further customization if needed
    """
    fig = plt.figure()

    ax1 = fig.add_subplot(3, 1, 1)
    ax2 = fig.add_subplot(3, 1, 2)
    ax3 = fig.add_subplot(3, 1, 3)

    # X axis
    ax1.plot(t[1:], data1_x, "b-", label="True Angle", linewidth=1.5)
    ax1.plot(t[1:], data2_x, "g--", label="Sensor Angle", linewidth=1.5)
    ax1.plot(t[1:], data3_x, "r-.", label="Kalman Angle", linewidth=1.5)
    ax1.set_title("X Axis")
    ax1.set_xlabel("Time")
    ax1.set_ylabel("Deg")
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    # Y axis
    ax2.plot(t[1:], data1_y, "b-", label="True Angle", linewidth=1.5)
    ax2.plot(t[1:], data2_y, "g--", label="Sensor Angle", linewidth=1.5)
    ax2.plot(t[1:], data3_y, "r-.", label="Kalman Angle", linewidth=1.5)
    ax2.set_title("Y Axis")
    ax2.set_xlabel("Time")
    ax2.set_ylabel("Deg")
    ax2.legend()
    ax2.grid(True, alpha=0.3)

    # Z axis
    ax3.plot(t[1:], data1_z, "b-", label="True Angle", linewidth=1.5)
    ax3.plot(t[1:], data2_z, "g--", label="Sensor Angle", linewidth=1.5)
    ax3.plot(t[1:], data3_z, "r-.", label="Kalman Angle", linewidth=1.5)
    ax3.set_title("Z Axis")
    ax3.set_xlabel("Time")
    ax3.set_ylabel("Deg")
    ax3.legend()
    ax3.grid(True, alpha=0.3)

    plt.tight_layout()


# Initialize global variables
t = [0.0]
data1_x = []
data1_y = []
data1_z = []
data2_x = []
data2_y = []
data2_z = []
data3_x = []
data3_y = []
data3_z = []

TIME_INTERVAL = 1.0

if __name__ == "__main__":
    import numpy as np

    # Get default or user input for number of points
    n_points = 100
    try:
        n_points_input = input("Enter number of data points: ").strip()
        if n_points_input:
            n_points = int(n_points_input)
    except (ValueError, EOFError):
        print("Using default value.")

    # Generate random Euler angle data with range [-45, 45] degrees
    for _ in range(n_points):
        euler1 = (
            np.random.uniform(-45, 45),
            np.random.uniform(-45, 45),
            np.random.uniform(-45, 45),
        )
        euler2 = (
            np.random.uniform(-45, 45),
            np.random.uniform(-45, 45),
            np.random.uniform(-45, 45),
        )
        euler3 = (
            np.random.uniform(-45, 45),
            np.random.uniform(-45, 45),
            np.random.uniform(-45, 45),
        )
        add_data(euler1, euler2, euler3)

    # Plot the data
    plot_data()
    plt.suptitle("Random Data Test")
    plt.tight_layout()
    plt.show()
